### PR TITLE
fix issue #19

### LINKED ISSUE #19: Fix message routes and use path params
Please make the following changes to the routes:

/get -> /:id
/delete -> /:id
/edit -> /:id
/getRoom -> /getRoom/:room

This change is necessary because the body of get and delete should not have any meaning. The other changes are to keep the body clean and only contain the updates.

The path parameter can be retrieved in the controller using req.param.{path-parameter-name}.

### PR DESCRIPTION
**Pull request by wenweil**

### CODE REVIEW

File: src/routes/message.js [hunk 1]
```diff
@@ -7,10 +7,10 @@ module.exports = [
     const router = new express.Router();
 
     router.post("/", auth,  msgController.newMessage);
-    router.get("/get", auth, msgController.getMessage);
-    router.delete("/delete", auth, msgController.deleteMessage);
-    router.patch("/edit", auth, msgController.editMessage);
-    router.get("/getRoom", auth, msgController.getRoom);
+    router.get("/get/:id", auth, msgController.getMessage);
```
Comment (wenhao-zhang) [inline src/routes/message.js]: Remove the method from the endpoint. There is no need to put the method in the endpoint. Keep the path short as possible and try to keep the naming similar to the other paths

Comment (wenweil) [reply src/routes/message.js]: okay

**Review by wenhao-zhang — APPROVED** [review]
LGTM
